truncate table drug_interactions, drug_aliases, allergy_cross_reactivity, drugs, patients restart identity cascade;

insert into drugs (generic_name, generic_name_normalized, drug_class, renal_dosing) values
('Amoxicillin','amoxicillin','Penicillin antibiotic','{"min_egfr":10,"dose_adjust":[{"below":30,"guidance":"Extend interval; review dose."}]}'),
('Amoxicillin-Clavulanate','amoxicillin-clavulanate','Penicillin antibiotic','{"min_egfr":10,"dose_adjust":[{"below":30,"guidance":"Use renal-adjusted dosing."}]}'),
('Azithromycin','azithromycin','Macrolide antibiotic','{"min_egfr":10}'),
('Clarithromycin','clarithromycin','Macrolide antibiotic','{"min_egfr":30,"dose_adjust":[{"below":60,"guidance":"Reduce dose by 50% when eGFR <60."}]}'),
('Ciprofloxacin','ciprofloxacin','Fluoroquinolone antibiotic','{"min_egfr":15,"dose_adjust":[{"below":30,"guidance":"Reduce dose or extend interval."}]}'),
('Levofloxacin','levofloxacin','Fluoroquinolone antibiotic','{"min_egfr":15,"dose_adjust":[{"below":50,"guidance":"Renal dose adjustment required."}]}'),
('Doxycycline','doxycycline','Tetracycline antibiotic','{"min_egfr":10}'),
('Trimethoprim-Sulfamethoxazole','trimethoprim-sulfamethoxazole','Sulfonamide antibiotic','{"min_egfr":15,"dose_adjust":[{"below":30,"guidance":"Reduce dose; avoid if severe renal impairment."}]}'),
('Vancomycin','vancomycin','Glycopeptide antibiotic','{"min_egfr":10,"dose_adjust":[{"below":60,"guidance":"Dose by levels and renal function."}]}'),
('Metformin','metformin','Biguanide','{"contraindicated_below":30,"dose_adjust":[{"below":45,"guidance":"Do not initiate; reassess risk/benefit."}]}'),
('Insulin Glargine','insulin-glargine','Long-acting insulin','{"min_egfr":10}'),
('Glipizide','glipizide','Sulfonylurea','{"min_egfr":10}'),
('Empagliflozin','empagliflozin','SGLT2 inhibitor','{"contraindicated_below":20}'),
('Lisinopril','lisinopril','ACE inhibitor','{"min_egfr":10,"monitor":"Monitor potassium and creatinine."}'),
('Losartan','losartan','ARB','{"min_egfr":10,"monitor":"Monitor potassium and creatinine."}'),
('Spironolactone','spironolactone','Mineralocorticoid receptor antagonist','{"contraindicated_below":30}'),
('Furosemide','furosemide','Loop diuretic','{"min_egfr":10}'),
('Hydrochlorothiazide','hydrochlorothiazide','Thiazide diuretic','{"avoid_below":30}'),
('Amlodipine','amlodipine','Calcium channel blocker','{"min_egfr":10}'),
('Metoprolol','metoprolol','Beta blocker','{"min_egfr":10}'),
('Diltiazem','diltiazem','Calcium channel blocker','{"min_egfr":10}'),
('Atorvastatin','atorvastatin','Statin','{"min_egfr":10}'),
('Simvastatin','simvastatin','Statin','{"min_egfr":10}'),
('Rosuvastatin','rosuvastatin','Statin','{"dose_adjust":[{"below":30,"guidance":"Start 5 mg; max 10 mg daily."}]}'),
('Warfarin','warfarin','Vitamin K antagonist','{"min_egfr":10}'),
('Apixaban','apixaban','DOAC','{"min_egfr":15,"monitor":"Assess age, weight, creatinine for dose criteria."}'),
('Rivaroxaban','rivaroxaban','DOAC','{"contraindicated_below":15}'),
('Clopidogrel','clopidogrel','Antiplatelet','{"min_egfr":10}'),
('Aspirin','aspirin','NSAID antiplatelet','{"avoid_below":30}'),
('Ibuprofen','ibuprofen','NSAID','{"avoid_below":60}'),
('Naproxen','naproxen','NSAID','{"avoid_below":60}'),
('Prednisone','prednisone','Corticosteroid','{"min_egfr":10}'),
('Omeprazole','omeprazole','PPI','{"min_egfr":10}'),
('Pantoprazole','pantoprazole','PPI','{"min_egfr":10}'),
('Levothyroxine','levothyroxine','Thyroid hormone','{"min_egfr":10}'),
('Sertraline','sertraline','SSRI','{"min_egfr":10}'),
('Fluoxetine','fluoxetine','SSRI','{"min_egfr":10}'),
('Citalopram','citalopram','SSRI','{"min_egfr":10}'),
('Tramadol','tramadol','Opioid analgesic','{"dose_adjust":[{"below":30,"guidance":"Extend interval; max 200 mg/day."}]}'),
('Morphine','morphine','Opioid analgesic','{"avoid_below":30}'),
('Oxycodone','oxycodone','Opioid analgesic','{"dose_adjust":[{"below":60,"guidance":"Start low and titrate cautiously."}]}'),
('Gabapentin','gabapentin','Anticonvulsant analgesic','{"dose_adjust":[{"below":30,"severity":"SEVERE","guidance":"At eGFR 15-29, use 100 mg once daily; avoid 300 mg TDS because accumulation and neurotoxicity risk are high."},{"below":60,"guidance":"Renal dose adjustment required."}]}'),
('Pregabalin','pregabalin','Anticonvulsant analgesic','{"dose_adjust":[{"below":60,"guidance":"Renal dose adjustment required."}]}'),
('Allopurinol','allopurinol','Xanthine oxidase inhibitor','{"dose_adjust":[{"below":60,"guidance":"Start low; titrate by urate and renal function."}]}'),
('Colchicine','colchicine','Antigout','{"contraindicated_below":30}'),
('Digoxin','digoxin','Cardiac glycoside','{"dose_adjust":[{"below":60,"guidance":"Use lower dose and monitor levels."}]}'),
('Amiodarone','amiodarone','Antiarrhythmic','{"min_egfr":10}'),
('Phenytoin','phenytoin','Anticonvulsant','{"min_egfr":10}'),
('Carbamazepine','carbamazepine','Anticonvulsant','{"min_egfr":10}'),
('Paracetamol','paracetamol','Analgesic antipyretic','{"min_egfr":10}'),
('Diclofenac','diclofenac','NSAID','{"avoid_below":60}'),
('Telmisartan','telmisartan','ARB','{"min_egfr":10,"monitor":"Monitor potassium and creatinine."}'),
('Methotrexate','methotrexate','Antimetabolite immunosuppressant','{"contraindicated_below":30,"dose_adjust":[{"below":60,"guidance":"Renal dose adjustment and specialist monitoring required."}]}');

insert into drug_aliases (alias, actual_drug) values
('augmentin','amoxicillin-clavulanate'),('tylenol','paracetamol'),('acetaminophen','paracetamol'),('gaba','gabapentin'),('clarithro','clarithromycin'),('azithro','azithromycin'),('bactrim','trimethoprim-sulfamethoxazole'),('co-trimoxazole','trimethoprim-sulfamethoxazole'),('lasix','furosemide'),('coumadin','warfarin'),('eliquis','apixaban'),('xarelto','rivaroxaban'),('plavix','clopidogrel'),('motrin','ibuprofen'),('advil','ibuprofen'),('synthroid','levothyroxine'),('voltaren','diclofenac'),('micardis','telmisartan'),('mtx','methotrexate');

insert into allergy_cross_reactivity (allergy_class, cross_reacts_with, cross_reactivity_pct, guidance) values
('penicillin','penicillin antibiotic',100,'Avoid penicillins in true anaphylaxis; use specialist-guided alternative.'),
('penicillin','cephalosporin antibiotic',2,'Assess reaction history; avoid high-risk beta-lactams in anaphylaxis.'),
('cephalosporin','penicillin antibiotic',2,'Assess side-chain similarity and reaction severity.'),
('sulfonamide','sulfonamide antibiotic',100,'Avoid sulfonamide antibiotics after severe sulfa reaction.'),
('macrolide','macrolide antibiotic',100,'Avoid class rechallenge after serious immediate reaction.'),
('fluoroquinolone','fluoroquinolone antibiotic',100,'Avoid fluoroquinolone class after severe reaction.'),
('nsaid','nsaid',80,'Avoid nonselective NSAIDs in cross-reactive NSAID hypersensitivity.'),
('opioid','opioid analgesic',20,'Differentiate intolerance from allergy; monitor if alternative opioid used.');

insert into drug_interactions (drug_a_normalized, drug_b_normalized, severity, mechanism, clinical_effect, management) values
('clarithromycin','atorvastatin','SEVERE','CYP3A4 inhibition raises statin exposure.','Myopathy and rhabdomyolysis.','Hold atorvastatin or use azithromycin.'),
('clarithromycin','amlodipine','MODERATE','CYP3A4 inhibition raises calcium-channel blocker exposure.','Hypotension, bradycardia, and acute kidney injury risk.','Prefer azithromycin or monitor blood pressure closely if unavoidable.'),
('clarithromycin','simvastatin','HARD_BLOCK','Strong CYP3A4 inhibition.','Life-threatening rhabdomyolysis.','Avoid combination; choose non-CYP3A4 macrolide.'),
('warfarin','trimethoprim-sulfamethoxazole','SEVERE','CYP2C9 inhibition and gut flora change.','Marked INR elevation and bleeding.','Avoid or preemptively reduce warfarin with close INR.'),
('warfarin','amiodarone','SEVERE','CYP inhibition increases warfarin effect.','Bleeding risk.','Reduce warfarin and monitor INR.'),
('warfarin','aspirin','SEVERE','Additive anticoagulant/antiplatelet effect.','Major bleeding.','Use only if compelling indication.'),
('apixaban','clarithromycin','SEVERE','P-gp/CYP3A4 inhibition.','Increased anticoagulant exposure.','Avoid or adjust per protocol.'),
('rivaroxaban','clarithromycin','SEVERE','P-gp/CYP3A4 inhibition.','Increased bleeding risk.','Prefer azithromycin or alternative.'),
('lisinopril','spironolactone','SEVERE','Additive potassium retention.','Hyperkalemia.','Avoid in high-risk CKD; monitor K closely.'),
('losartan','spironolactone','SEVERE','Additive potassium retention.','Hyperkalemia.','Avoid in high-risk CKD; monitor K closely.'),
('lisinopril','ibuprofen','MODERATE','Afferent/efferent renal hemodynamic effect.','AKI risk.','Avoid NSAIDs; monitor renal function.'),
('losartan','ibuprofen','MODERATE','Renal hemodynamic interaction.','AKI risk.','Avoid NSAIDs; monitor renal function.'),
('telmisartan','diclofenac','MODERATE','ARB plus NSAID reduces renal autoregulation; risk is higher with dehydration or diuretics.','Acute kidney injury and hyperkalemia risk.','Avoid NSAID exposure and monitor creatinine/potassium if already taken.'),
('furosemide','ibuprofen','MODERATE','NSAID blunts diuretic effect.','Fluid retention and renal injury.','Use acetaminophen when possible.'),
('aspirin','ibuprofen','MODERATE','Competitive COX-1 binding and additive NSAID toxicity.','Reduced aspirin cardioprotection and increased GI/renal toxicity.','Avoid routine combination; separate dosing only if clinician-directed.'),
('digoxin','amiodarone','SEVERE','P-gp inhibition raises digoxin levels.','Digoxin toxicity.','Reduce digoxin dose and monitor levels.'),
('digoxin','clarithromycin','SEVERE','P-gp inhibition and gut flora effect.','Digoxin toxicity.','Avoid or monitor level closely.'),
('metformin','ciprofloxacin','MODERATE','Fluoroquinolones alter glycemic control.','Hypo/hyperglycemia.','Monitor glucose.'),
('citalopram','clarithromycin','SEVERE','Additive QT prolongation.','Torsades de pointes.','Avoid combination; ECG if unavoidable.'),
('amiodarone','levofloxacin','SEVERE','Additive QT prolongation.','Torsades de pointes.','Avoid or monitor ECG/electrolytes.'),
('amiodarone','azithromycin','MODERATE','Additive QT prolongation.','Arrhythmia risk.','Monitor ECG and electrolytes.'),
('sertraline','tramadol','SEVERE','Serotonergic synergy.','Serotonin syndrome and seizures.','Avoid or choose non-serotonergic analgesic.'),
('fluoxetine','tramadol','SEVERE','Serotonergic synergy and CYP2D6 inhibition.','Serotonin syndrome; reduced analgesia.','Avoid combination.'),
('gabapentin','oxycodone','MODERATE','Additive CNS/respiratory depression.','Sedation and respiratory depression.','Use lowest doses and monitor.'),
('pregabalin','oxycodone','MODERATE','Additive CNS depression.','Sedation and falls.','Use caution and monitor.'),
('colchicine','clarithromycin','HARD_BLOCK','CYP3A4/P-gp inhibition sharply raises colchicine.','Fatal colchicine toxicity.','Contraindicated.'),
('allopurinol','amoxicillin','MODERATE','Immune-mediated rash risk increased.','Severe rash risk.','Counsel and monitor; consider alternative.'),
('phenytoin','warfarin','MODERATE','Complex CYP/protein binding interaction.','INR instability.','Monitor INR and phenytoin levels.'),
('carbamazepine','apixaban','SEVERE','Strong CYP3A4/P-gp induction lowers DOAC.','Thromboembolism risk.','Avoid combination.'),
('carbamazepine','rivaroxaban','SEVERE','Strong CYP3A4/P-gp induction lowers DOAC.','Thromboembolism risk.','Avoid combination.'),
('diltiazem','simvastatin','SEVERE','CYP3A4 inhibition.','Myopathy/rhabdomyolysis.','Limit simvastatin dose or switch statin.'),
('omeprazole','clopidogrel','MODERATE','CYP2C19 inhibition reduces activation.','Reduced antiplatelet effect.','Prefer pantoprazole.');

insert into patients (id, name, age, sex, race, weight_kg, diagnoses, medications, allergies, labs, vitals, history) values
('P-1001','Maya Srinivasan',72,'female','unspecified',58,'["Atrial fibrillation","CKD stage 3b","Type 2 diabetes"]','["Warfarin","Atorvastatin","Metformin","Lisinopril"]','["Penicillin anaphylaxis"]','{"scr_mg_dl":1.7,"egfr_ml_min":32,"potassium_mmol_l":4.9,"inr":2.4}','{"bp":"136/78","hr":88,"spo2":96}','{"chf":true,"hypertension":true,"diabetes":true,"stroke_tia":false,"vascular_disease":true}'),
('P-1002','Robert Chen',64,'male','unspecified',83,'["Heart failure","Hypertension"]','["Lisinopril","Furosemide","Spironolactone","Metoprolol"]','["NSAID bronchospasm"]','{"scr_mg_dl":1.3,"egfr_ml_min":62,"potassium_mmol_l":5.2}','{"bp":"118/70","hr":71,"spo2":98}','{"chf":true,"hypertension":true,"diabetes":false,"stroke_tia":false,"vascular_disease":false}'),
('P-1003','Elena Garcia',81,'female','unspecified',51,'["Atrial fibrillation","Prior TIA","Osteoarthritis"]','["Apixaban","Diltiazem","Paracetamol"]','["Sulfonamide rash"]','{"scr_mg_dl":1.1,"egfr_ml_min":49}','{"bp":"128/66","hr":79,"spo2":97}','{"chf":false,"hypertension":true,"diabetes":false,"stroke_tia":true,"vascular_disease":false}'),
('P-1004','James Walker',55,'male','unspecified',94,'["Type 2 diabetes","Hyperlipidemia"]','["Metformin","Empagliflozin","Rosuvastatin"]','[]','{"scr_mg_dl":0.9,"egfr_ml_min":102,"hba1c_pct":7.4}','{"bp":"124/76","hr":66,"spo2":99}','{"chf":false,"hypertension":false,"diabetes":true,"stroke_tia":false,"vascular_disease":false}'),
('P-1005','Aisha Khan',39,'female','unspecified',67,'["Cellulitis","Migraine"]','["Sertraline","Omeprazole"]','["Macrolide urticaria"]','{"scr_mg_dl":0.8,"egfr_ml_min":95}','{"bp":"110/64","hr":84,"spo2":99}','{"chf":false,"hypertension":false,"diabetes":false,"stroke_tia":false,"vascular_disease":false}'),
('P-1006','Thomas Reed',68,'male','unspecified',76,'["CAD","Atrial fibrillation","CKD stage 4"]','["Rivaroxaban","Aspirin","Amiodarone","Digoxin"]','["Fluoroquinolone anaphylaxis"]','{"scr_mg_dl":2.4,"egfr_ml_min":27,"potassium_mmol_l":4.7}','{"bp":"130/72","hr":62,"spo2":95}','{"chf":true,"hypertension":true,"diabetes":false,"stroke_tia":false,"vascular_disease":true}'),
('P-1007','Priya Menon',47,'female','unspecified',72,'["Gout","Hypertension"]','["Allopurinol","Losartan","Hydrochlorothiazide"]','["Penicillin rash"]','{"scr_mg_dl":1.0,"egfr_ml_min":71,"uric_acid_mg_dl":8.1}','{"bp":"142/86","hr":74,"spo2":99}','{"chf":false,"hypertension":true,"diabetes":false,"stroke_tia":false,"vascular_disease":false}'),
('P-1008','Linda Brooks',78,'female','unspecified',63,'["Neuropathic pain","COPD","CKD stage 3a"]','["Gabapentin","Oxycodone","Prednisone"]','["Morphine angioedema"]','{"scr_mg_dl":1.2,"egfr_ml_min":46}','{"bp":"126/68","hr":91,"spo2":92}','{"chf":false,"hypertension":true,"diabetes":false,"stroke_tia":false,"vascular_disease":false}'),
('P-1009','Daniel Evans',59,'male','unspecified',88,'["Seizure disorder","DVT"]','["Phenytoin","Warfarin","Pantoprazole"]','[]','{"scr_mg_dl":1.0,"egfr_ml_min":86,"inr":1.9}','{"bp":"122/74","hr":69,"spo2":98}','{"chf":false,"hypertension":false,"diabetes":false,"stroke_tia":false,"vascular_disease":true}'),
('P-1010','Grace Okafor',70,'female','unspecified',69,'["Depression","Long QT","Pneumonia"]','["Citalopram","Amlodipine","Simvastatin"]','["Cephalosporin hives"]','{"scr_mg_dl":1.4,"egfr_ml_min":39,"potassium_mmol_l":4.1,"magnesium_mg_dl":1.8}','{"bp":"134/80","hr":82,"spo2":94}','{"chf":false,"hypertension":true,"diabetes":false,"stroke_tia":false,"vascular_disease":false}');
