PATIENTS = [
    {
        "id": "P-1001",
        "name": "Maya Srinivasan",
        "age": 72,
        "sex": "female",
        "weight_kg": 58,
        "diagnoses": ["Atrial fibrillation", "CKD stage 3b", "Type 2 diabetes"],
        "medications": ["Warfarin", "Atorvastatin", "Metformin", "Lisinopril"],
        "allergies": ["Penicillin anaphylaxis"],
        "labs": {"scr_mg_dl": 1.7, "egfr_ml_min": 32, "potassium_mmol_l": 4.9, "inr": 2.4},
        "vitals": {"bp": "136/78", "hr": 88, "spo2": 96},
        "history": {"chf": True, "hypertension": True, "diabetes": True, "stroke_tia": False, "vascular_disease": True},
    },
    {
        "id": "P-1002",
        "name": "Robert Chen",
        "age": 64,
        "sex": "male",
        "weight_kg": 83,
        "diagnoses": ["Heart failure", "Hypertension"],
        "medications": ["Lisinopril", "Furosemide", "Spironolactone", "Metoprolol"],
        "allergies": ["NSAID bronchospasm"],
        "labs": {"scr_mg_dl": 1.3, "egfr_ml_min": 62, "potassium_mmol_l": 5.2},
        "vitals": {"bp": "118/70", "hr": 71, "spo2": 98},
        "history": {"chf": True, "hypertension": True, "diabetes": False, "stroke_tia": False, "vascular_disease": False},
    },
    {
        "id": "P-1003",
        "name": "Elena Garcia",
        "age": 81,
        "sex": "female",
        "weight_kg": 51,
        "diagnoses": ["Atrial fibrillation", "Prior TIA", "Osteoarthritis"],
        "medications": ["Apixaban", "Diltiazem", "Paracetamol"],
        "allergies": ["Sulfonamide rash"],
        "labs": {"scr_mg_dl": 1.1, "egfr_ml_min": 49},
        "vitals": {"bp": "128/66", "hr": 79, "spo2": 97},
        "history": {"chf": False, "hypertension": True, "diabetes": False, "stroke_tia": True, "vascular_disease": False},
    },
    {
        "id": "P-1004",
        "name": "James Walker",
        "age": 55,
        "sex": "male",
        "weight_kg": 94,
        "diagnoses": ["Type 2 diabetes", "Hyperlipidemia"],
        "medications": ["Metformin", "Empagliflozin", "Rosuvastatin"],
        "allergies": [],
        "labs": {"scr_mg_dl": 0.9, "egfr_ml_min": 102, "hba1c_pct": 7.4},
        "vitals": {"bp": "124/76", "hr": 66, "spo2": 99},
        "history": {"chf": False, "hypertension": False, "diabetes": True, "stroke_tia": False, "vascular_disease": False},
    },
    {
        "id": "P-1005",
        "name": "Aisha Khan",
        "age": 39,
        "sex": "female",
        "weight_kg": 67,
        "diagnoses": ["Cellulitis", "Migraine"],
        "medications": ["Sertraline", "Omeprazole"],
        "allergies": ["Macrolide urticaria"],
        "labs": {"scr_mg_dl": 0.8, "egfr_ml_min": 95},
        "vitals": {"bp": "110/64", "hr": 84, "spo2": 99},
        "history": {"chf": False, "hypertension": False, "diabetes": False, "stroke_tia": False, "vascular_disease": False},
    },
    {
        "id": "P-1006",
        "name": "Thomas Reed",
        "age": 68,
        "sex": "male",
        "weight_kg": 76,
        "diagnoses": ["CAD", "Atrial fibrillation", "CKD stage 4"],
        "medications": ["Rivaroxaban", "Aspirin", "Amiodarone", "Digoxin"],
        "allergies": ["Fluoroquinolone anaphylaxis"],
        "labs": {"scr_mg_dl": 2.4, "egfr_ml_min": 27, "potassium_mmol_l": 4.7},
        "vitals": {"bp": "130/72", "hr": 62, "spo2": 95},
        "history": {"chf": True, "hypertension": True, "diabetes": False, "stroke_tia": False, "vascular_disease": True},
    },
    {
        "id": "P-1007",
        "name": "Priya Menon",
        "age": 47,
        "sex": "female",
        "weight_kg": 72,
        "diagnoses": ["Gout", "Hypertension"],
        "medications": ["Allopurinol", "Losartan", "Hydrochlorothiazide"],
        "allergies": ["Penicillin rash"],
        "labs": {"scr_mg_dl": 1.0, "egfr_ml_min": 71, "uric_acid_mg_dl": 8.1},
        "vitals": {"bp": "142/86", "hr": 74, "spo2": 99},
        "history": {"chf": False, "hypertension": True, "diabetes": False, "stroke_tia": False, "vascular_disease": False},
    },
    {
        "id": "P-1008",
        "name": "Linda Brooks",
        "age": 78,
        "sex": "female",
        "weight_kg": 63,
        "diagnoses": ["Neuropathic pain", "COPD", "CKD stage 3a"],
        "medications": ["Gabapentin", "Oxycodone", "Prednisone"],
        "allergies": ["Morphine angioedema"],
        "labs": {"scr_mg_dl": 1.2, "egfr_ml_min": 46},
        "vitals": {"bp": "126/68", "hr": 91, "spo2": 92},
        "history": {"chf": False, "hypertension": True, "diabetes": False, "stroke_tia": False, "vascular_disease": False},
    },
    {
        "id": "P-1009",
        "name": "Daniel Evans",
        "age": 59,
        "sex": "male",
        "weight_kg": 88,
        "diagnoses": ["Seizure disorder", "DVT"],
        "medications": ["Phenytoin", "Warfarin", "Pantoprazole"],
        "allergies": [],
        "labs": {"scr_mg_dl": 1.0, "egfr_ml_min": 86, "inr": 1.9},
        "vitals": {"bp": "122/74", "hr": 69, "spo2": 98},
        "history": {"chf": False, "hypertension": False, "diabetes": False, "stroke_tia": False, "vascular_disease": True},
    },
    {
        "id": "P-1010",
        "name": "Grace Okafor",
        "age": 70,
        "sex": "female",
        "weight_kg": 69,
        "diagnoses": ["Depression", "Long QT", "Pneumonia"],
        "medications": ["Citalopram", "Amlodipine", "Simvastatin"],
        "allergies": ["Cephalosporin hives"],
        "labs": {"scr_mg_dl": 1.4, "egfr_ml_min": 39, "potassium_mmol_l": 4.1, "magnesium_mg_dl": 1.8},
        "vitals": {"bp": "134/80", "hr": 82, "spo2": 94},
        "history": {"chf": False, "hypertension": True, "diabetes": False, "stroke_tia": False, "vascular_disease": False},
    },
]
